---
- hosts: iojs-build-fedora20

  remote_user: root

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    - name: General | yum Update
      yum: name=* state=latest
      tags: general

    - name: General | Install required packages
      yum: name={{ item }} state=latest
      with_items: packages
      tags: general

    - name: NTP | Run initial NTP
      command: ntpdate -u pool.ntp.org
      tags: ntp

    - name: NTP | Enable NTP
      command: chkconfig ntpd on
      tags: ntp

    - name: NTP | Start NTP
      service: name=ntpd state=started enabled=yes
      tags: ntp

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash
      tags: user

    - name: User | Download pubkey(s)
      get_url: url=https://github.com/{{ item }}.keys dest=/tmp/{{ item }}.keys
      delegate_to: 127.0.0.1
      with_items: ssh_users
      tags: user

    - name: General | Create authorized_keys for root
      authorized_key: user="root" key="{{ lookup('file', '/tmp/' + item + '.keys') }}"
      with_items: ssh_users
      tags: user

    - name: General | Create authorized_keys for {{ server_user }}
      authorized_key: user="{{ server_user }}" key="{{ lookup('file', '/tmp/' + item + '.keys') }}"
      with_items: ssh_users
      tags: user

    - name: Jenkins | Download Jenkins' slave.jar
      command: curl -sL https://ci.nodejs.org/jnlpJars/slave.jar -o /home/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Jenkins | Install jenkins.service
      template: src=./resources/jenkins.service.j2 dest=/lib/systemd/system/jenkins.service

    - name: Jenkins | Start Jenkins service
      service: name=jenkins state=started
      tags: jenkins
