---
- hosts: node-www
  remote_user: root

  tasks:
    - include_vars: ansible-vars.yaml
      tags: vars

    - include: tasks/user.yaml
      tags: user

    - include: tasks/docker.yaml
      tags: docker

    - include: tasks/site-setup.yaml
      tags: setup

    - include: tasks/cloudfuse.yaml
      tags: cloudfuse

    - include: tasks/webhook.yaml
      tags: webhook

    - include: tasks/nginx.yaml
      tags: nginx

    - include: tasks/dist-indexer.yaml
      tags: dist-indexer

    - include: tasks/nightly-builder.yaml
      tags: nightly-builder

