---
- hosts: iojs-build-centos6

  remote_user: root

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    #- name: General | Download EPEL RPM
    #  command: curl -sL http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm -o /tmp/epel-release-6-8.noarch.rpm
    #  tags: general

    #- name: General | Install EPEL RPM
    #  command: bash -c 'rpm -Uvh /tmp/epel-release-6-8.noarch.rpm || true'
    #  tags: general

    - name: General | yum Update
      yum: name=* state=latest
      tags: general

    - name: General | Add SLC devtoolset repo
      command: curl -sL http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo -o /etc/yum.repos.d/slc6-devtoolset.repo
      tags: general

    - name: General | Add SLC devtoolset repo GPG key
      command: rpm --import http://ftp.scientificlinux.org/linux/scientific/5x/x86_64/RPM-GPG-KEYs/RPM-GPG-KEY-cern
      tags: general

    - name: General | Download SLC SCL repo config
      command: curl http://linuxsoft.cern.ch/cern/scl/slc6-scl.repo -o /etc/yum.repos.d/slc6-scl.repo
      tags: general

    - name: General | Install required packages
      yum: name={{ item }} state=latest
      with_items: packages
      tags: general

    - name: General | Increase file descriptor limits
      lineinfile: dest=/etc/security/limits.conf line="{{ item }}"
      with_items:
        - "*         hard    nofile      500000"
        - "*         soft    nofile      500000"
        - "root      hard    nofile      500000"
        - "root      soft    nofile      500000"
      tags: general

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash
      tags: user

    - name: User | Download pubkey(s)
      get_url: url=https://github.com/{{ item }}.keys dest=/tmp/{{ item }}.keys
      delegate_to: 127.0.0.1
      with_items: ssh_users
      tags: user

    - name: General | Create authorized_keys for root
      authorized_key: user="root" key="{{ lookup('file', '/tmp/' + item + '.keys') }}"
      with_items: ssh_users
      tags: user

    - name: General | Create authorized_keys for {{ server_user }}
      authorized_key: user="{{ server_user }}" key="{{ lookup('file', '/tmp/' + item + '.keys') }}"
      with_items: ssh_users
      tags: user

    - name: Jenkins | Download Jenkins' slave.jar
      command: curl -sL https://jenkins-iojs.nodesource.com/jnlpJars/slave.jar -o /home/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Jenkins | Copy start.sh script
      copy: src=./resources/start.sh dest=/home/{{ server_user }}/start.sh owner={{ server_user }} group={{ server_user }} mode=0755
      tags: jenkins

    - name: Jenkins | Copy secret to start.sh script
      replace: dest=/home/{{ server_user }}/start.sh regexp="\{\{secret\}\}" replace="{{ server_secret }}"
      tags: jenkins

    - name: Jenkins | Copy GCC 4.4 secret to start.sh script
      replace: dest=/home/{{ server_user }}/start.sh regexp="\{\{gcc44_secret\}\}" replace="{{ gcc44_server_secret }}"
      tags: jenkins

    - name: Jenkins | Copy server id to start.sh script
      replace: dest=/home/{{ server_user }}/start.sh regexp="\{\{id\}\}" replace="{{ server_id }}"
      tags: jenkins

    - name: Jenkins | Copy GCC 4.4 server id to start.sh script
      replace: dest=/home/{{ server_user }}/start.sh regexp="\{\{gcc44_id\}\}" replace="{{ gcc44_server_id }}"
      tags: jenkins
